### ISSUE TITLE
 Manual DynCSS cache clearing not triggered

### ISSUE THREAD

**Issue by mkoitka** [kaystrobach/TYPO3.dyncss#20] opened 2015-09-14 11:37 UTC
First of all nice work so far, big thanks for that!

The manual DynCSS cache clearing button does not work for me in a TYPO3 6.2 installation. I did some debugging and the 'clearCachePostProc'-Function of the hook is never called.

Comparing the URLs of the cache clearing buttons, the one from DynCSS is slightly different from the others.

**URL of "System Cache" button**
...typo3/tce_db.php?vC=8f8e1dca89&cacheCmd=system...

**URL of "DynCSS Cache" button**
...typo3/mod.php?M=tce_db&moduleToken=0c5856978e7d64014ffaf2540cd6653c817ba5a4&vC=...

After telling the "DynCSS Cache" button to also directly use **tce_db.php** cache clearing works perfectly.

I changed line 34 of the file dyncss/Classes/Hooks/Backend/Toolbar/ClearCacheActionsHook.php

from ...
```'href' => BackendUtility::getModuleUrl('tce_db') . '&vC=' . $this->getBackendUser()->veriCode() . '&cacheCmd=dyncss&ajaxCall=1' . BackendUtility::getUrlToken('tceAction'),```

to ...
```'href' => 'tce_db.php?vC=' . $this->getBackendUser()->veriCode() . '&cacheCmd=dyncss&ajaxCall=1' . BackendUtility::getUrlToken('tceAction'),```

However, it could be that has some drawbacks for TYPO3 7.x, because **mod.php** seems to be used there by default.

--

*Btw I also wrote an issue on forge.typo3.org. Is Github generally the preferred issue tracker for this project?*

**Comment by kaystrobach** [comment] 2015-09-14 11:39
@mkoitka yes currently we prefer github as this is more agile an open then SVN ;)

I will take a look into that thingy, IMHO we use a core API to generate the URI, what i prefer over coding that statically (with all the hashes, crypto, etc.)

**Comment by mkoitka** [comment] 2015-09-14 11:45
Ok, nice to know :)

**Comment by kaystrobach** [comment] 2015-09-29 14:30
i can't reproduce that right now :hushed:

**Comment by mkoitka** [comment] 2015-09-30 14:04
Hmm... weird. I now had a closer look and could also get an exception message.
```
No module "tce_db" could be found. 
```
It's thrown in mod.php line 46, because the dispatcher can't call/find that module.

I should say, that for me this is no longer an urgent issue as we will be using DynCSS only for TYPO3 7.x.

**Comment by fazzyx** [comment] 2016-01-20 15:12
I have the same problem. TYPO3 6.2.17, dyncss 0.7.8, dyncss_less 0.7.6.
Error: No module "tce_db" could be found.

**Comment by kaystrobach** [comment] 2016-01-20 15:20
mhmm think i will disable that feature for 6.x soon :cry:

**Comment by fazzyx** [comment] 2016-01-20 15:49
Cause it is not possible to get it work under 6.x?

**Comment by stefanschleich** [comment] 2016-01-21 13:45
What's wrong with this workaround by hensoko? https://github.com/kaystrobach/TYPO3.dyncss/issues/26

**Comment by kaystrobach** [comment] 2016-01-21 13:58
Its not working in 7.6 and i dislike to add deprecated Code

Von meinem iPhone gesendet

**Comment by kaystrobach** [comment] 2016-04-18 06:58
should be fixed in master no

**Closed by kaystrobach** 2016-04-18 06:58 UTC
