### ISSUE TITLE
[critical] full server path in URL

### ISSUE THREAD

**Issue by Lobster1956** [kaystrobach/TYPO3.dyncss#13] opened 2015-04-28 01:11 UTC
hi... i'm using **dyncss 0.7.3** and **dyncss.less 0.7.2**

in my css i have relative paths... the new path is build relativly correctly, but in the new url in the dynamic css there is the full server path inside...
In the less file in: `http://domain.tld/home/fileadmin/template/css/style.less`
i have the relative path: `../images/file.jpg`
I would expect: `http://domain.tld/fileadmin/template/images/file.jpg`
but i get: `http://domain.tld/home/www/html/fileadmin/template/images/file.jpg`
The `home/www/html/` is the server path to my docroot ??? what is missing im my installation ???

**Comment by kaystrobach** [comment] 2015-04-28 05:42
@Lobster1956 currently we have no testcases for fileadmin, as we normally put the less files in extensions.

But i will take a look at it in the next days.

**Comment by kaystrobach** [comment] 2015-04-28 05:49
which version of dyncss are you using?

**Comment by kaystrobach** [comment] 2015-04-28 05:51
have you tried using something like

```
/fileadmin/image.png
```

**Comment by Lobster1956** [comment] 2015-04-28 08:53
Am 28.04.2015 um 07:49 schrieb Kay Strobach:
>
> which version of dyncss are you using?
>
as i wrote: i'm using *dyncss 0.7.3* and *dyncss.less 0.7.2*

-- 
Signatur: RRS IF *image[FORMAT]* . . . /wir geben Ihrem Image das
richtige Format/
Direktkontakt       . . . *Ralf-René Schröder  +49 (0)3721 / 287 147*
^*DGSV <http://schroeder-ralf-rene.dgusv.de/>* / *DGA
<http://www.deutsche-gutachterauskunft.de/gutachter-ralf-rene-schroeder-1299.html>*
zert. Sachverständiger für /'Werbegutachten und Medienwesen'/

*image[FORMAT]* - Inh. B. Müller
Stollberger Strasse 22-24 | 09380 Thalheim / Erzgeb.

eMAIL: verwaltung@image-format.eu <mailto:verwaltung@image-format.eu>
WWW: http://www.image-format.eu
TEL:     +49 (0)3721 / 35 91 37
FAX:     +49 (0)3721 / 28 72 60

**Comment by kaystrobach** [comment] 2015-04-28 08:54
saw it after reformatting the issue ...

**Comment by Lobster1956** [comment] 2015-04-28 09:10
Am 28.04.2015 um 07:51 schrieb Kay Strobach:
>
> have you tried using something like
>
> |/fileadmin/image.png|
|yes, absolute paths are OK, only relative paths get the additional
serverpath,
but the relativation (??? sorry for bad englisch) itself is also OK..
(DE: also die relative Anpassung zur CSS Datei ist OK, nur alles vor
fileadmin gehört natürlich nicht in die URL)...
|||

-- 
Signatur: RRS IF *image[FORMAT]* . . . /wir geben Ihrem Image das
richtige Format/
Direktkontakt       . . . *Ralf-René Schröder  +49 (0)3721 / 287 147*
^*DGSV <http://schroeder-ralf-rene.dgusv.de/>* / *DGA
<http://www.deutsche-gutachterauskunft.de/gutachter-ralf-rene-schroeder-1299.html>*
zert. Sachverständiger für /'Werbegutachten und Medienwesen'/

*image[FORMAT]* - Inh. B. Müller
Stollberger Strasse 22-24 | 09380 Thalheim / Erzgeb.

eMAIL: verwaltung@image-format.eu <mailto:verwaltung@image-format.eu>
WWW: http://www.image-format.eu
TEL:     +49 (0)3721 / 35 91 37
FAX:     +49 (0)3721 / 28 72 60

**Comment by kaystrobach** [comment] 2015-04-28 12:14
due to the movement of files in the temp folders, we need absolute path in the end ... i will try to find a solution for that was well ...

**Comment by kaystrobach** [comment] 2015-09-09 06:22
the latest git master should fix that, would be happy for a review :smile:

**Comment by Lobster1956** [comment] 2015-09-27 09:24
sorry for late testing...
now relative paths (one in a line) will be parsed correctly, but multi backgrounds not...
background-image: url("../../images/file1.png"), url("../../images/file2.png"); 
is parsed to:
background-image: url("../../fileadmin/correct-path/images/file1.png"), url("../..");

and now absolut paths won't work (or i don't know how to set them?)
background-image:url("/fileadmin/correct-path/images/file1.png"); 
is parsed to:
background-image: url("");

**Comment by kaystrobach** [comment] 2015-09-28 05:37
just to sum up we have:

* url(/<...>)
* url(<...>);
* url(<...>//<...>); external https:// or http://

anything missing?

If not i will try to add more tests for that stuff

**Comment by Lobster1956** [comment] 2015-09-28 11:41
i think this is all... maybe file:/// with three slashes, but for this the 2 slashes test shoud work ???

background: url(img_flwr.gif) right bottom no-repeat, url(paper.gif) left top repeat;
and the url could also url('...') or url("...")
and it could be much more than two urls

**Comment by kaystrobach** [comment] 2015-09-28 12:02
how should the file protocoll work with an TYPO3 installation? you can't access local files (neither of the user, nor of the server) ...

**Comment by kaystrobach** [comment] 2015-09-28 12:32
are you able to provide a testing css file, which i can add to my postprocessing tests? this way we can clearly say, what works, and what breaks :smile:

**Comment by realJustmike** [comment] 2015-09-29 14:30
dyncss 0.7.4
dyncss_scss 0.7.1

I have the following path in my style.scss (typo3conf/ext/theme_gugler_bootstrap_ipp/Resources/Private/Dyncss/Library/style.scss):

url(../../../Public/Images/m_menu.svg)

The image is located in:
typo3conf/ext/theme_gugler_bootstrap_ipp/Resources/Public/Images/m_menu.svg

The resulting path in the compiled css file looks like this: ?!

../../../../typo3conf/ext/theme_gugler_bootstrap_ipp/Resources/Private/Dyncss/Library/../../../../typo3conf/ext/theme_gugler_bootstrap_ipp/Resources/Private/Dyncss/Library/../../../../typo3conf/ext/theme_gugler_bootstrap_ipp/Resources/Private/Dyncss/Library/../../../Public/Images/m_menu.svg

**Comment by kaystrobach** [comment] 2015-09-29 15:24
@realJustmike is it the same with current master? or is it different?

**Comment by kaystrobach** [comment] 2015-09-29 15:55
especially the last commit d76f959 should fix quite some stuff :smiley_cat:

**Comment by kaystrobach** [comment] 2015-09-29 16:20
the first tests are in place, the more problematic code you give me, the more robust can i make that functionality ... 

see https://github.com/kaystrobach/TYPO3.dyncss/blob/master/Tests/Unit/Parser/DummyParserTest.php#L14 as an example

**Comment by Lobster1956** [comment] 2015-09-29 23:27
THANKS... your modifications work (especialy multi parsing in one row for multiple backgrounds)...
another code in CSS is filter or -ms-filter... there is the url NOT in url(<...>) but in:
src='<...>' or src="<...>"
like in: -ms-filter: progid:DXImageTransform.Microsoft.AlphaImageLoader( src='../../ContentData/symbole/wissenswertes.png', sizingMethod='scale');

**Comment by kaystrobach** [comment] 2015-09-30 05:44
@lobster1956 any chance to sponsor that ms-filter fixing with one hour or so? Invoice will be provided ;)

**Comment by realJustmike** [comment] 2015-09-30 09:42
I tried it with current master but the resulting path is still the same (removed typo3temp/ completely before ... ).

../../../../typo3conf/ext/theme_gugler_bootstrap_ipp/Resources/Private/Dyncss/Library/../../../../typo3conf/ext/theme_gugler_bootstrap_ipp/Resources/Private/Dyncss/Library/../../../../typo3conf/ext/theme_gugler_bootstrap_ipp/Resources/Private/Dyncss/Library/../../../Public/Images/m_menu.svg

**Comment by kaystrobach** [comment] 2015-09-30 10:06
Can you please add the following information:

* location of your less file
* location of the image
* less / scss code for uri part
* expected path/uri
* is it working right now and just a styling thingy?

Thanks in advice

----- Originale Nachricht -----
Von: realJustmike <notifications@github.com>
Gesendet: 30.09.2015 - 11:42
An: "kaystrobach/TYPO3.dyncss" <TYPO3.dyncss@noreply.github.com>
Betreff: Re: [TYPO3.dyncss] [critical] full server path in URL (#13)

**Comment by realJustmike** [comment] 2015-09-30 11:01
* my scss-file:
typo3conf/ext/theme_gugler_bootstrap_ipp/Resources/Private/Dyncss/Library/style.scss
* the image:
typo3conf/ext/theme_gugler_bootstrap_ipp/Resources/Public/Images/m_menu.svg
* scss url:
url(../../../Public/Images/m_menu.svg)
* expected path:
a working one ;)
* working now?
no, the image cannot be downloaded by the browser. 404. Because the resulting path in the css file is not working:
../../../../typo3conf/ext/theme_gugler_bootstrap_ipp/Resources/Private/Dyncss/Library/../../../../typo3conf/ext/theme_gugler_bootstrap_ipp/Resources/Private/Dyncss/Library/../../../../typo3conf/ext/theme_gugler_bootstrap_ipp/Resources/Private/Dyncss/Library/../../../Public/Images/m_menu.svg

**Comment by Lobster1956** [comment] 2015-09-30 16:46
@kaystrobach (ich mache das mal auf deutsch)
leider habe ich hierzu keinen Kunden, der es dringend braucht (bis jetzt konnte ich mir in dem Fall  bei-ms-filter mit dem absoluten Pfad helfen, weil er ja nicht geparsed wird...
Aber ich greif mal in die eigene Tasche... ist zwar keine ganze Stunde, aber über 50€ kannst du imageFORMAT eine Rechnung schreiben damit das hier komplett funktioniert (denn ich setze dyncss gerne ein)...

**Comment by kaystrobach** [comment] 2015-09-30 16:56
ok, will deliver and then I will send the invoice :smile: thanks a lot!

**Comment by kaystrobach** [comment] 2015-10-05 07:28
@realJustmike 

how have you included your scss file:

```
page.includeCSS.testLess = EXT:theme_gugler_bootstrap_ipp/Resources/Private/Dyncss/Library/style.scss
```

or with the full path instead?

**Comment by kaystrobach** [comment] 2015-10-05 07:47
@Lobster1956 can you please retest the latest master, i added a new test and some code to fix your problem.

**Comment by realJustmike** [comment] 2015-10-19 09:49
@kaystrobach 
I included it by setting the Theme-Constant "themes.configuration.mainCssFile" to the following value:
EXT:theme_gugler_bootstrap_ipp/Resources/Private/Dyncss/Library/styles-budget.scss

**Comment by kaystrobach** [comment] 2015-10-19 09:51
and the images pathes are relative to you scss file? wonder why it works for all the other people ... :cry:

**Comment by hummal** [comment] 2015-12-16 07:07
Its not working for all other people. Having the same problem as @realJustmike

**Comment by kaystrobach** [comment] 2015-12-16 07:09
@hummal have you tried the latest version if so and it is still an issue, please post sample code, that nails down the problem (just the view problematic lines, that you pass to the compiler)

**Comment by hummal** [comment] 2015-12-16 07:11
dyncss 0.7.8 TER
dyncss_scss 1.0.2 TER

Sample Code:
.info_open {
        background-image: url(../Icons/icon_arrow_white_right.png);
}

SCSS Result:
.tx_ehfeos .groupListMatches .row.info_open {
        background-image: url(../../../../typo3conf/ext/ehf_eos/Resources/Public/Stylesheets/../../../../typo3conf/ext/ehf_eos/Resources/Public/Stylesheets/../Icons/icon_arrow_white_right.png);
       }

**Comment by kaystrobach** [comment] 2015-12-16 07:12
and what do you get as output?

**Comment by hummal** [comment] 2015-12-16 07:13
The SCSS Result ist the ouput in the browser

**Comment by kaystrobach** [comment] 2015-12-16 07:14
see, main problem is, that the path is not _resolved_ to the shortest possible way to point to a file - right?

**Comment by hummal** [comment] 2015-12-16 07:15
Yes, the valid path would be:

`.tx_ehfeos .groupListMatches .row.info_open {
background-image: url(../../../../typo3conf/ext/ehf_eos/Resources/Public/Icons/icon_arrow_white_right.png);
}`

**Comment by kaystrobach** [comment] 2015-12-16 07:17
but still the path should be pointing to the correct file, so it's not a critical bug, but more a cosmetical thingy, please be aware that the path is calculated from the location of the scss output (in typo3temp)

**Comment by hummal** [comment] 2015-12-16 07:18
Do you see the doubled path strings?
I got two times `../../../../typo3conf/ext/ehf_eos/Resources/Public/Stylesheets/`

**Comment by kaystrobach** [comment] 2015-12-16 07:21
is your image in a different package as the scss file?
if not, why do you make the path in a way, that you put the extension in it again?
if it is in the same package, please just make the image path relative to the scss file ...

**Comment by hummal** [comment] 2015-12-16 07:23
I guess I found the problem.

Full SCSS:

`&.info_open {
        background-image: url(../Icons/icon_arrow_white_right.png);
        background: $row no-repeat scroll center right;
        cursor: pointer;
        &.even {
          background-image: url(../Icons/icon_arrow_white_right.png);
          background: $rowEven no-repeat scroll center right;

        }
      }
      &.info_close {
        background-image: url(../Icons/icon_arrow_white_down.png);
        background: $eventColor  no-repeat scroll center right;
        color: #fff;
      }`

If I just change the second and third line of background img to 
`background-image: url(/../Icons/icon_arrow_white_right.png);`
it works for the &.info_open line. This is because the other 2 paths are wrong then.

Maybe there is a problem for the same path is set more than one time in short.

If I use the background image url 3 times the path is wrong.

**Comment by hummal** [comment] 2015-12-16 07:24
As you can see in the last post, there are relative paths

**Comment by kaystrobach** [comment] 2015-12-16 07:25
mhmm, ok, maybe the relative dumb replacement algorithm needs some refinement, i will check if i can reproduce that as a testcase and then i will try to deliver a fix

interested in sponsoring?

**Comment by hummal** [comment] 2015-12-16 07:27
Thank you for your effort. 
Iam doing this extension for free for a friend. So I can't afford any money for sponsoring this. Iam sorry. 
Just want to help you finding the problem in the parser. For me I can use absolute paths in the scss also. It is not the good way, but a working one for now.

Thx

**Comment by kaystrobach** [comment] 2015-12-16 07:56
anyway i will try to find it, but not today :smile: 

sponsoring can also be time for finding a problem or solving it.
If you want https://github.com/kaystrobach/TYPO3.dyncss/blob/master/Classes/Parser/AbstractParser.php#L120 should be the problematic code part

**Comment by hummal** [comment] 2015-12-16 08:53
Found it!
`
if(is_array($matches) && count($matches)) {
			foreach($matches as $key => $value) {
				$url = trim($value['url'], '\'"');
				$newPath = $this->resolveUrlInCss($url);
				$string = str_replace($url, $newPath, $string);
			}
		}
`
In your str_replace at line 136 you search for the needle "../Icons/icon_arrow_white_right.png" and replace it with "../../../../typo3conf/ext/ehf_eos/Resources/Public/Stylesheets/../Icons/icon_arrow_white_right.png"!
The problem is, if I use more than 1 time the same url for an image it will be doubled or tripled or n'led if I use the url n times.

I'll try to find a fix for this.

**Comment by kaystrobach** [comment] 2015-12-16 08:54
the replace should replace the whole line … in the matches should be one field with the whole line

**Comment by hummal** [comment] 2015-12-16 08:55
But you will have an array of matches with 3 times the same line and it will replace it all the time again. I just debugged it already

**Comment by hummal** [comment] 2015-12-16 08:56
The array of matches exists before the foreach and so the matches are still there even if they are already replaced

**Comment by kaystrobach** [comment] 2015-12-16 08:56
but if the whole line is replaced instead of just a path fragment there should be no problem, as in the second run it won’t match :D

**Comment by hummal** [comment] 2015-12-16 08:57
It will match:

"../Icons/icon_arrow_white_right.png" is still in the already replaced path of the first entry: "../../../../typo3conf/ext/ehf_eos/Resources/Public/Stylesheets/../Icons/icon_arrow_white_right.png"

**Comment by kaystrobach** [comment] 2015-12-16 08:59
not what i meant ...

* `../Icons/icon_arrow_white_right.png`
* `        background-image: url(../Icons/icon_arrow_white_right.png);`

the first is the path fragment, the second one is the whole line ... the matches array should be multivalued and one value should be the whole line ... if not the regex may need some changes :smile:

**Comment by hummal** [comment] 2015-12-16 09:00
![2015-12-16 09_59_02-](https://cloud.githubusercontent.com/assets/633711/11836547/b20503f2-a3db-11e5-97ca-e4ee8a1795d2.png)

Matches array

**Comment by kaystrobach** [comment] 2015-12-16 09:00
dammit ... then the regex does not catch everything ...

**Comment by hummal** [comment] 2015-12-16 09:02
But if we use the index 0 instead of "url" and put the "url()" around the $newPath it should work, shouldnt it?

**Comment by hummal** [comment] 2015-12-16 09:13
Created a pull request #30. Check it if it fits your needs.

**Comment by kaystrobach** [comment] 2019-02-06 09:53
as https://github.com/kaystrobach/TYPO3.dyncss/pull/30 is merged - i close that one here

**Closed by kaystrobach** 2019-02-06 09:53 UTC
Labels: bug
